[package]
name = "event-driven_ingest"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
chrono = "0.4.38"
serde_json = "1"
wit-bindgen = "0.30"